name: Build + Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #     cache: 'yarn'
      #     cache-dependency-path: 'app/yarn.lock'

      # - name: Install Backend
      #   run: yarn install
      #   working-directory: ./app

      # - name: Test Backend
      #   run: yarn test
      #   working-directory: ./app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CD_ROLE }}
          role-duration-seconds: 900
          aws-region: eu-west-2

      - name: Upload Artifact to s3
        run: aws deploy push \
          --application-name ${{ secrets.CD_APPNAME }} \
          --source app/ \
          --s3-location s3://${{ secrets.S3BUCKET }}/app_package.zip \
          --ignore-hidden-files

      - name: Deploy code
        run: aws deploy create-deployment \
          --application-name ${{ secrets.CD_APPNAME }} \
          --deployment-group-name ${{ secrets.CD_GROUPNAME }} \
          --s3-location bucket=${{ secrets.S3BUCKET }},key=app_package.zip,bundleType=zip \
          --file-exists-behavior OVERWRITE
